[package]
name = "sauce"
version = "0.1.0"
edition = "2021"

[workspace]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
rustyline = "10.0.0"
tracing = "0.1.37"
lisp-parser = { path = "src/lisp-parser" }